name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    env:
      NEXT_PUBLIC_CLERK_FRONTEND_API: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Run the application locally
        run: |
          nohup npm run start &

      - name: Install Cypress
        run: npm install cypress

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          config: baseUrl=http://localhost:3000
